"""
LAKV-v2: SharedPrefixPipeline
==============================

Architecturally correct 2-agent KV relay.

Design
------
Both agents begin from an IDENTICAL shared prefix:

    <system>SHARED_SYSTEM_PROMPT</system>
    <user>question</user>
    <assistant>              ← generation_prompt

Agent 0 (Solver):
  • Runs forward pass on the shared prefix.
  • Continues greedy decoding for up to `solver_max_new_tokens` tokens.
  • The full KV cache (prefix + reasoning) is captured.

LAKV Transfer:
  • LayerSelector (optional) drops Tier-3 layers.
  • KVCompressor (optional) quantises remaining layers.
  • KVMessage transmitted to Agent 1.

Agent 1 (Finalizer):
  • Decompresses + reconstructs the received KV.
  • Processes a SHORT SUFFIX (not a new full prompt):
        finalizer_suffix tokens
  • position_ids = [cache_seq_len, cache_seq_len+1, ...]
    → mathematically correct RoPE continuation.
  • Greedy decodes the final answer.

Two transfer modes
------------------
  'full'   — transfer prefix + reasoning KV (Agent 1 skips prefix re-encoding)
  'tail'   — transfer reasoning tail only; Agent 1 re-encodes the shared
             prefix itself, then continues with reasoning tail KV
             (saves bandwidth for the shared prefix)

This module is completely independent of the old v1 pipeline.
It imports only kv_compressor and layer_selector.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import torch
from transformers import DynamicCache

# Reuse existing compression / selection modules (no changes needed there)
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
from kv_compressor import KVCompressor, KVMessage
from layer_selector import LayerSelector, SelectionMask


# ── constants ─────────────────────────────────────────────────────────────────

SHARED_SYSTEM_PROMPT = (
    "You are a careful mathematical reasoning assistant. "
    "Solve accurately and provide correct final answers."
)

# Default short continuation suffix for the Finalizer.
# This is appended as raw tokens directly after the Solver's KV cache —
# it does NOT repeat the question or system prompt.
DEFAULT_FINALIZER_SUFFIX = "\nFinal answer: ####"

# Alternative slightly richer suffix for ablation
VERIFY_FINALIZER_SUFFIX = "\nCheck the reasoning above. Final answer: ####"


# ── config ────────────────────────────────────────────────────────────────────

@dataclass
class SharedPrefixConfig:
    # Shared prompt (both agents see this as their prefix)
    shared_system_prompt: str = SHARED_SYSTEM_PROMPT

    # Finalizer suffix — appended after Solver KV, NOT a new prompt
    finalizer_suffix: str = DEFAULT_FINALIZER_SUFFIX

    # Solver reasoning budget (tokens generated by Solver)
    solver_max_new_tokens: int = 64          # default; use 96 for richer reasoning
    finalizer_max_new_tokens: int = 32       # answer is short (#### N)

    # KV transfer mode
    transfer_mode: str = "full"              # 'full' | 'tail'

    # Layer selection (set selector on the pipeline instance directly)
    use_layer_selection: bool = False

    # Compression mode: 'none' | 'uniform_int8' | 'uniform_int4' | 'adaptive'
    compression_mode: str = "none"

    # Reconstruction strategy for dropped layers: 'zeros' | 'nearest' | 'interpolate'
    reconstruction_strategy: str = "zeros"

    # Profile path — required for adaptive compression / layer selection
    profile_path: Optional[str] = None

    # Logging
    print_raw_outputs: bool = False
    verbose: bool = False


# ── result ────────────────────────────────────────────────────────────────────

@dataclass
class SharedPrefixResult:
    answer: str
    solver_reasoning: str          # decoded text from Solver's generated tokens
    latency_s: float
    transfer_mode: str

    # Cache shape info
    prefix_len: int                # shared prefix token count
    solver_gen_len: int            # tokens Solver generated
    cache_seq_len: int             # total tokens in transferred KV
    suffix_len: int                # Finalizer suffix tokens

    # Layer / compression stats
    n_layers_transferred: int      # how many layers sent
    n_layers_total: int = 28
    original_mb: float = 0.0
    compressed_mb: float = 0.0
    compression_ratio: float = 1.0


# ── pipeline ──────────────────────────────────────────────────────────────────

class SharedPrefixPipeline:
    """
    LAKV-v2: two-agent relay with shared prefix + suffix continuation.

    Usage:
        cfg = SharedPrefixConfig(transfer_mode='full', compression_mode='none')
        pipe = SharedPrefixPipeline(model, tokenizer, cfg, device='cuda')
        result = pipe.run("Janet's ducks lay 16 eggs per day...")
        print(result.answer)
    """

    N_LAYERS = 28

    def __init__(
        self,
        model,
        tokenizer,
        config: SharedPrefixConfig,
        device: str = "cuda",
        selector: Optional[LayerSelector] = None,
    ):
        self.model = model
        self.tokenizer = tokenizer
        self.config = config
        self.device = device

        # Selector injected externally (or built from profile_path)
        self.selector = selector
        if selector is None and config.use_layer_selection and config.profile_path:
            from calibration_profiler import LayerProfile
            profile = LayerProfile.load(config.profile_path)
            self.selector = LayerSelector(profile)

        self.compressor = KVCompressor(
            mode=config.compression_mode,
            profile=self._load_profile() if config.compression_mode == "adaptive" else None,
        )

    # ── public API ────────────────────────────────────────────────────────

    def run(self, question: str) -> SharedPrefixResult:
        t0 = time.time()

        # ── Phase 1: Build shared prefix ──────────────────────────────────
        messages = [
            {"role": "system", "content": self.config.shared_system_prompt},
            {"role": "user",   "content": question},
        ]
        prefix_text = self.tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        prefix_ids = self.tokenizer(
            prefix_text, return_tensors="pt", add_special_tokens=False
        )["input_ids"].to(self.device)
        prefix_len = prefix_ids.shape[1]

        # ── Phase 2: Solver forward pass on prefix → then greedy decode ───
        with torch.no_grad():
            prefix_out = self.model(
                input_ids=prefix_ids,
                use_cache=True,
            )
        running_cache = prefix_out.past_key_values  # DynamicCache after prefix
        next_logits = prefix_out.logits[:, -1, :]   # logits for first new token

        eos_id = self.tokenizer.eos_token_id
        generated_ids: List[int] = []

        for _ in range(self.config.solver_max_new_tokens):
            next_token = next_logits.argmax(-1, keepdim=True)  # (1,1)
            tok_id = next_token.item()
            if tok_id == eos_id:
                break
            generated_ids.append(tok_id)
            with torch.no_grad():
                out = self.model(
                    input_ids=next_token,
                    past_key_values=running_cache,
                    use_cache=True,
                )
            running_cache = out.past_key_values
            next_logits = out.logits[:, -1, :]

        solver_reasoning = self.tokenizer.decode(generated_ids, skip_special_tokens=True)
        solver_gen_len = len(generated_ids)

        # Full KV = prefix + reasoning tokens
        full_kv_tuple = self._to_tuple(running_cache)
        # full_kv_tuple[layer][0].shape == (1, n_kv_heads, prefix_len+solver_gen_len, head_dim)

        if self.config.verbose:
            print(f"  [Solver] prefix_len={prefix_len} | generated={solver_gen_len} tokens")
            print(f"  [Solver] reasoning: {solver_reasoning[:120]}...")

        # ── Phase 3: LAKV Transfer ────────────────────────────────────────
        kv_to_transfer, transferred_cache_seq_len = self._build_transfer_kv(
            full_kv_tuple, prefix_ids, prefix_len, question
        )

        # Layer selection
        selection_mask: Optional[SelectionMask] = None
        tier_info: Optional[Dict[int, int]] = None
        if self.selector is not None:
            kv_to_transfer, selection_mask = self.selector.select(kv_to_transfer)
            tier_info = selection_mask.tier_per_kept_layer
            n_transferred = len(selection_mask.kept_layer_indices)
        else:
            n_transferred = self.N_LAYERS

        # Compression
        layer_indices = selection_mask.kept_layer_indices if selection_mask else None
        kv_message = self.compressor.compress(
            kv_to_transfer,
            tier_info=tier_info,
            layer_indices=layer_indices,
        )
        original_mb = kv_message.original_bytes / 1e6
        compressed_mb = kv_message.compressed_bytes / 1e6
        compression_ratio = kv_message.compression_ratio

        if self.config.verbose:
            print(f"  [Transfer] mode={self.config.transfer_mode} | "
                  f"layers={n_transferred}/28 | "
                  f"orig={original_mb:.2f}MB | comp={compressed_mb:.2f}MB | "
                  f"ratio={compression_ratio:.2f}x")

        # Decompression
        decompressed = self.compressor.decompress(kv_message, device=self.device)

        # Reconstruct full 28-layer tuple for dropped layers
        if self.selector is not None and selection_mask is not None:
            decompressed = self.selector.reconstruct(
                decompressed,
                selection_mask,
                strategy=self.config.reconstruction_strategy,
            )

        # ── Phase 4: Finalizer suffix continuation ────────────────────────
        answer = self._run_finalizer(
            decompressed,
            transferred_cache_seq_len,
            full_kv_tuple,
            prefix_ids,
            prefix_len,
        )

        if self.config.print_raw_outputs:
            print(f"\n[RAW Solver]    {solver_reasoning}")
            print(f"[RAW Finalizer] {answer}\n")

        latency = time.time() - t0

        # Suffix token count (for logging)
        suffix_ids = self.tokenizer(
            self.config.finalizer_suffix, return_tensors="pt", add_special_tokens=False
        )["input_ids"]
        suffix_len = suffix_ids.shape[1]

        return SharedPrefixResult(
            answer=answer,
            solver_reasoning=solver_reasoning,
            latency_s=latency,
            transfer_mode=self.config.transfer_mode,
            prefix_len=prefix_len,
            solver_gen_len=solver_gen_len,
            cache_seq_len=transferred_cache_seq_len,
            suffix_len=suffix_len,
            n_layers_transferred=n_transferred,
            n_layers_total=self.N_LAYERS,
            original_mb=original_mb,
            compressed_mb=compressed_mb,
            compression_ratio=compression_ratio,
        )

    # ── transfer mode helpers ─────────────────────────────────────────────

    def _build_transfer_kv(
        self,
        full_kv_tuple: tuple,
        prefix_ids: torch.Tensor,
        prefix_len: int,
        question: str,
    ) -> Tuple[tuple, int]:
        """
        Return (kv_to_transfer, cache_seq_len_for_receiver).

        'full' mode:
            Transfer the entire prefix+reasoning KV.
            Finalizer continues from position cache_seq_len.

        'tail' mode:
            Agent 1 recomputes the shared prefix itself (identical to Agent 0's),
            then we transfer only the REASONING TAIL KV.
            Agent 1 merges its own prefix KV + received tail KV.
            This saves bandwidth for the shared prefix.
        """
        if self.config.transfer_mode == "full":
            cache_seq_len = full_kv_tuple[0][0].shape[2]
            return full_kv_tuple, cache_seq_len

        elif self.config.transfer_mode == "tail":
            # Slice out only the reasoning tail
            tail_kv = self._slice_reasoning_tail(full_kv_tuple, prefix_len)
            # Agent 1 will re-encode the prefix → position offset = prefix_len + tail_len
            tail_len = tail_kv[0][0].shape[2]

            # Re-encode prefix for Agent 1 to get prefix KV
            with torch.no_grad():
                prefix_out = self.model(input_ids=prefix_ids, use_cache=True)
            prefix_kv = self._to_tuple(prefix_out.past_key_values)

            # Concatenate prefix KV + tail KV along sequence dimension
            merged_kv = self._concat_kv(prefix_kv, tail_kv)
            cache_seq_len = merged_kv[0][0].shape[2]
            return merged_kv, cache_seq_len

        else:
            raise ValueError(f"Unknown transfer_mode: {self.config.transfer_mode!r}. "
                             f"Use 'full' or 'tail'.")

    @staticmethod
    def _slice_reasoning_tail(full_kv: tuple, prefix_len: int) -> tuple:
        """Return KV sliced to only the reasoning portion [prefix_len:]."""
        return tuple(
            (k[:, :, prefix_len:, :], v[:, :, prefix_len:, :])
            for k, v in full_kv
        )

    @staticmethod
    def _concat_kv(kv_a: tuple, kv_b: tuple) -> tuple:
        """Concatenate two KV caches along the sequence dimension (dim=2)."""
        assert len(kv_a) == len(kv_b), "KV tuples must have same number of layers"
        return tuple(
            (torch.cat([ka, kb], dim=2), torch.cat([va, vb], dim=2))
            for (ka, va), (kb, vb) in zip(kv_a, kv_b)
        )

    # ── finalizer ─────────────────────────────────────────────────────────

    def _run_finalizer(
        self,
        injected_kv: tuple,
        cache_seq_len: int,
        full_kv_tuple: tuple,
        prefix_ids: torch.Tensor,
        prefix_len: int,
    ) -> str:
        """
        Finalizer: process the suffix tokens as a CONTINUATION of injected_kv.

        position_ids start at cache_seq_len — this is the KEY correctness fix.
        No new prompt is built. Only the short suffix is processed.
        """
        # Tokenize the finalizer suffix
        suffix_ids = self.tokenizer(
            self.config.finalizer_suffix,
            return_tensors="pt",
            add_special_tokens=False,
        )["input_ids"].to(self.device)
        suffix_len = suffix_ids.shape[1]

        # Convert to DynamicCache
        cache = self._to_dynamic_cache(injected_kv)

        # ── CRITICAL: position_ids = continuation from cache end ──────────
        position_ids = torch.arange(
            cache_seq_len,
            cache_seq_len + suffix_len,
            device=self.device,
        ).unsqueeze(0)  # (1, suffix_len)

        # Forward pass: suffix tokens attending over the full solver KV
        with torch.no_grad():
            out = self.model(
                input_ids=suffix_ids,
                past_key_values=cache,
                position_ids=position_ids,
                use_cache=True,
            )

        running_cache = out.past_key_values
        next_logits = out.logits[:, -1, :]

        # Greedy decode the answer (short — just a number)
        eos_id = self.tokenizer.eos_token_id
        generated: List[int] = []

        for _ in range(self.config.finalizer_max_new_tokens):
            next_token = next_logits.argmax(-1, keepdim=True)
            tok_id = next_token.item()
            if tok_id == eos_id:
                break
            generated.append(tok_id)
            with torch.no_grad():
                out = self.model(
                    input_ids=next_token,
                    past_key_values=running_cache,
                    use_cache=True,
                )
            running_cache = out.past_key_values
            next_logits = out.logits[:, -1, :]

        return self.tokenizer.decode(generated, skip_special_tokens=True)

    # ── cache conversion ──────────────────────────────────────────────────

    @staticmethod
    def _to_tuple(pkv) -> tuple:
        if isinstance(pkv, tuple):
            return pkv
        if isinstance(pkv, DynamicCache):
            if hasattr(pkv, "to_legacy_cache"):
                return pkv.to_legacy_cache()
            layers = []
            for layer in pkv:
                if isinstance(layer, tuple):
                    layers.append((layer[0], layer[1]))
                else:
                    layers.append((layer.keys, layer.values))
            return tuple(layers)
        if hasattr(pkv, "__iter__"):
            layers = []
            for layer in pkv:
                if isinstance(layer, tuple):
                    layers.append((layer[0], layer[1]))
                else:
                    layers.append((layer.keys, layer.values))
            if layers:
                return tuple(layers)
        return pkv

    @staticmethod
    def _to_dynamic_cache(kv_tuple: tuple) -> DynamicCache:
        if isinstance(kv_tuple, DynamicCache):
            return kv_tuple
        if hasattr(DynamicCache, "from_legacy_cache"):
            return DynamicCache.from_legacy_cache(kv_tuple)
        return DynamicCache(kv_tuple)

    # ── profile loader ────────────────────────────────────────────────────

    def _load_profile(self):
        if not self.config.profile_path:
            raise ValueError("profile_path required for adaptive compression")
        from calibration_profiler import LayerProfile
        return LayerProfile.load(self.config.profile_path)
